In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix

In [17]:
df=pd.read_csv('Wholesale customers data.csv')

In [18]:
df.columns

Index(['Channel', 'Region', 'Fresh', 'Milk', 'Grocery', 'Frozen',
       'Detergents_Paper', 'Delicassen'],
      dtype='object')

In [19]:
df.head()

   Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656     7561     214              2674        1338
1        2       3   7057  9810     9568    1762              3293        1776
2        2       3   6353  8808     7684    2405              3516        7844
3        1       3  13265  1196     4221    6404               507        1788
4        2       3  22615  5410     7198    3915              1777        5185

In [20]:
df.groupby('Channel').mean().round(0)

,Region,Fresh,Milk,Grocery,Frozen,Detergents_Paper,Delicassen
Channel,,,,,,,
1,3.0,13476.0,3452.0,3962.0,3748.0,791.0,1416.0
2,3.0,8904.0,10716.0,16323.0,1653.0,7270.0,1753.0

In [21]:
# channel is our target variable
# 1- horeca and, 2- retail
import numpy as np

In [22]:
X=df.drop(['Channel','Region','Delicassen'],axis=1)
y=df['Channel']

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=20)

In [24]:
scaling=ColumnTransformer([
    ('scaler',StandardScaler(),X_train.columns)
])
model=Pipeline([
    ('scale',scaling),
    ('naive_baise',GaussianNB())
])

In [25]:
model.fit(X_train,y_train)

Pipeline(steps=[('scale',
                 ColumnTransformer(transformers=[('scaler', StandardScaler(),
                                                  Index(['Fresh', 'Milk', 'Grocery', 'Frozen', 'Detergents_Paper'], dtype='object'))])),
                ('naive_baise', GaussianNB())])

In [26]:
y_pred=model.predict(X_test)

In [27]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=50, scoring="f1")
print("Mean f1:", scores.mean())

Mean f1: 0.9274891774891775

In [28]:
print('accuracy:',accuracy_score(y_test,y_pred))
print("precision",precision_score(y_test,y_pred))
print('recall',recall_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

accuracy: 0.9090909090909091
precision 0.9444444444444444
recall 0.918918918918919
[[68  6]
 [ 4 32]]
              precision    recall  f1-score   support

           1       0.94      0.92      0.93        74
           2       0.84      0.89      0.86        36

    accuracy                           0.91       110
   macro avg       0.89      0.90      0.90       110
weighted avg       0.91      0.91      0.91       110

In [29]:
import pickle
with open('Project_Customer_Category_Classification.pkl','wb') as file:
    pickle.dump(model,file)

In [30]:
X_train.columns

Index(['Fresh', 'Milk', 'Grocery', 'Frozen', 'Detergents_Paper'], dtype='object')